DROP TABLE IF EXISTS seo_scores CASCADE;
DROP TABLE IF EXISTS seo_metadata CASCADE;
DROP TABLE IF EXISTS seo_internal_links CASCADE;
DROP TABLE IF EXISTS seo_audits CASCADE;
DROP TABLE IF EXISTS seo_clusters CASCADE;
DROP TABLE IF EXISTS seo_keywords CASCADE;
DROP TABLE IF EXISTS seo_projects CASCADE;
